name: pytest/mypy/ruff

on: 
  push:
    branches: 
      - dev
    paths:
      - 'btd6bot/**'
      - 'tests/**'
    paths-ignore:
      - 'btd6bot/plans/**'
      - 'btd6bot/_ocr_tests/**'


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev repository
        with:
          ref: dev
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock
      - name: Run tests
        run: |
          pytest

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev repository
        with:
          ref: dev
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy==1.19.1
      - name: Run type checks
        run: |
          mypy --install-types --non-interactive

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev repository
        with:
          ref: dev
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint codebase with ruff
        run: |
          ruff check